name: Run PowerShell Script

on:
  workflow_dispatch:
  push:
    branches:
      - test-branch

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell script
        shell: pwsh
        run: ./test.ps1

      - name: List files
        shell: pwsh
        run: Get-ChildItem