name: Run PowerShell Script

on:
  workflow_dispatch:
    inputs:
      scriptPath:
        description: Path to PowerShell script
        required: true
        default: Path_to_script_here

jobs:
  run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Output Folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path Output

      - name: Run Script
        shell: pwsh
        run: |
          $path = "${{ github.event.inputs.scriptPath }}"
          & $path

      - name: Upload Outputs
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.run_number }}
          path: Output/**
          if-no-files-found: ignore