name: Run PowerShell Script

on:
  workflow_dispatch:
    inputs:
      scriptPath:
        description: Path to PowerShell script
        required: true
        default: Path_to_script_here

jobs:
  run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Script
        shell: pwsh
        run: |
          $path = "${{ github.event.inputs.scriptPath }}"
          & $path